# Liber Terra MVP allowlist: lore metadata for shipped works.
# Gutenberg entries use `id`. URL entries set `source` to txt/html/epub/pdf.
# Titles are short display names for in-game books.

MVP_WORKS = [
    # Old English
    {
        "id": 981,
        "code": "beowulf",
        "title": "Beowulf",
        "group": "oldenglish",
        "filename": "Beowulf_Modern_English_Gummere.txt",
    },
    {
        "id": 657,
        "code": "anglosaxonchronicle",
        "title": "The Anglo-Saxon Chronicle",
        "group": "oldenglish",
        "filename": "The_Anglo_Saxon_Chronicle.txt",
    },
    {
        "id": 38326,
        "code": "bedeecclesiastical",
        "title": "Bede's Ecclesiastical History",
        "group": "oldenglish",
        "filename": "Bedes_Ecclesiastical_History_of_England.txt",
    },
    {
        "id": 618,
        "code": "codexjunius",
        "title": "Codex Junius 11",
        "group": "oldenglish",
        "filename": "Codex_Junius_11_Caedmon_manuscript.txt",
    },
    {
        "id": 31172,
        "code": "oldenglishpoems",
        "title": "Old English Poems",
        "group": "oldenglish",
        "filename": "Old_English_Poems_Selected_Translations.txt",
    },
    {
        "id": 15879,
        "code": "elenejudith",
        "title": "Elene, Judith, and Other Poems",
        "group": "oldenglish",
        "filename": "Elene_Judith_Athelstan_Byrhtnoth_Garnett.txt",
    },
    {
        "id": 10672,
        "code": "chessgame",
        "title": "Game and Playe of the Chesse",
        "group": "oldenglish",
        "filename": "Game_and_Playe_of_the_Chesse.txt",
    },
    # Early Middle English
    {
        "id": 26413,
        "code": "earlymiddleenglish",
        "title": "Selections from Early Middle English",
        "group": "earlyme",
        "filename": "Selections_from_Early_Middle_English_1130_1250_Part1_Texts.txt",
    },
    {
        "id": 14305,
        "code": "layamonbrut",
        "title": "Layamon's Brut",
        "group": "earlyme",
        "filename": "Layamons_Brut.txt",
    },
    {
        "id": 32049,
        "code": "havelok",
        "title": "The Lay of Havelok the Dane",
        "group": "earlyme",
        "filename": "The_Lay_of_Havelok_the_Dane.txt",
    },
    {
        "id": 42713,
        "code": "kinghorn",
        "title": "King Horn",
        "group": "earlyme",
        "filename": "King_Horn_Floriz_and_Blauncheflur.txt",
    },
    # Old French
    {
        "id": 391,
        "code": "songofroland",
        "title": "The Song of Roland",
        "group": "oldfrench",
        "filename": "The_Song_of_Roland.txt",
    },
    {
        "id": 831,
        "code": "chretienromances",
        "title": "Four Arthurian Romances",
        "group": "oldfrench",
        "filename": "Four_Arthurian_Romances_Chretien_de_Troyes.txt",
    },
    {
        "id": 10472,
        "code": "wacebrut",
        "title": "Wace: Roman de Brut",
        "group": "oldfrench",
        "filename": "Arthurian_Chronicles_Roman_de_Brut_Wace.txt",
    },
    {
        "id": 11417,
        "code": "mariedefrance",
        "title": "Lays of Marie de France",
        "group": "oldfrench",
        "filename": "Lays_of_Marie_de_France.txt",
    },
    {
        "id": 1578,
        "code": "aucassin",
        "title": "Aucassin and Nicolete",
        "group": "oldfrench",
        "filename": "Aucassin_and_Nicolete_Lang.txt",
    },
    # Middle High German
    {
        "id": 1151,
        "code": "nibelungenlied",
        "title": "The Nibelungenlied",
        "group": "mhg",
        "filename": "The_Nibelungenlied_Shumway.txt",
    },
    # Old Norse
    {
        "id": 347,
        "code": "grettir",
        "title": "The Saga of Grettir the Strong",
        "group": "oldnorse",
        "filename": "Saga_of_Grettir_the_Strong.txt",
    },
    {
        "id": 598,
        "code": "heimskringla",
        "title": "Heimskringla",
        "group": "oldnorse",
        "filename": "Heimskringla_Chronicle_of_Kings_of_Norway.txt",
    },
    {
        "id": 1152,
        "code": "volsunga",
        "title": "The Volsunga Saga",
        "group": "oldnorse",
        "filename": "Volsunga_Saga_with_Poetic_Edda_excerpts.txt",
    },
    {
        "id": 597,
        "code": "burntnjal",
        "title": "The Story of Burnt Njal",
        "group": "oldnorse",
        "filename": "Story_of_Burnt_Njal.txt",
    },
    # Welsh
    {
        "id": 5160,
        "code": "mabinogion",
        "title": "The Mabinogion",
        "group": "welsh",
        "filename": "The_Mabinogion_Guest.txt",
    },
    {
        "id": 1972,
        "code": "nennius",
        "title": "Historia Brittonum",
        "group": "welsh",
        "filename": "Historia_Brittonum_Nennius.txt",
    },
    # Ancient Irish
    {
        "id": 16464,
        "code": "irishepic",
        "title": "Táin Bó Cúalnge",
        "group": "ancientirish",
        "filename": "The_Ancient_Irish_Epic_Tain_Bo_Cualnge.txt",
    },
    # Medieval Latin
    {
        "id": 58655,
        "code": "gestaromanorum",
        "title": "Tales from the Gesta Romanorum",
        "group": "medievallatin",
        "filename": "Tales_from_the_Gesta_Romanorum.txt",
    },
    {
        "id": 14328,
        "code": "boethius",
        "title": "The Consolation of Philosophy",
        "group": "medievallatin",
        "filename": "Boethius_Consolation_of_Philosophy.txt",
    },
    {
        "id": 6032,
        "code": "villehardouin",
        "title": "Villehardouin: Chronicle of the Fourth Crusade",
        "group": "medievallatin",
        "filename": "Villehardouin_Chronicle_Fourth_Crusade.txt",
    },
    # --- Batch 2: ~50 more pre-1300 works ---
    # Old Norse / Icelandic
    {
        "id": 18947,
        "code": "proseedda",
        "title": "The Prose Edda",
        "group": "oldnorse",
        "filename": "The_Younger_Edda_Also_called_Snorres_Edda_or_The_Prose_Edda.txt",
    },
    {
        "id": 14726,
        "code": "elderedda",
        "title": "The Elder Edda",
        "group": "oldnorse",
        "filename": "The_Elder_Eddas_of_Saemund_Sigfusson_and_the_Younger_Eddas_of_Snorre_S.txt",
    },
    {
        "id": 17803,
        "code": "laxdaela",
        "title": "Laxdaela Saga",
        "group": "oldnorse",
        "filename": "Laxdaela_Saga.txt",
    },
    {
        "id": 17946,
        "code": "eirik",
        "title": "Eirik the Red's Saga",
        "group": "oldnorse",
        "filename": "Eirik_the_Reds_Saga.txt",
    },
    {
        "id": 24421,
        "code": "gunnlaug",
        "title": "Gunnlaug the Worm-Tongue",
        "group": "oldnorse",
        "filename": "Story_of_Gunnlaug_the_Worm_Tongue.txt",
    },
    {
        "id": 24420,
        "code": "frithiof",
        "title": "The Story of Frithiof the Bold",
        "group": "oldnorse",
        "filename": "Story_of_Frithiof_the_Bold.txt",
    },
    {
        "id": 22093,
        "code": "olafharald",
        "title": "Sagas of Olaf Tryggvason and Harald",
        "group": "oldnorse",
        "filename": "The_sagas_of_Olaf_Tryggvason_and_of_Harald_the_Tyrant_Harald_Haardraad.txt",
    },
    {
        "id": 18299,
        "code": "haco",
        "title": "Haco's Expedition Against Scotland",
        "group": "oldnorse",
        "filename": "The_Norwegian_account_of_Hacos_expedition_against_Scotland_AD_MCCLXIII.txt",
    },
    # Old French / German romance
    {
        "id": 2414,
        "code": "cliges",
        "title": "Cliges",
        "group": "oldfrench",
        "filename": "Cliges_Chretien_de_Troyes.txt",
    },
    {
        "id": 5988,
        "code": "oldfrenchromances",
        "title": "Old French Romances",
        "group": "oldfrench",
        "filename": "Old_French_Romances_Morris.txt",
    },
    {
        "id": 41163,
        "code": "romanderou",
        "title": "Wace: Roman de Rou",
        "group": "oldfrench",
        "filename": "Master_Wace_Roman_de_Rou_Norman_Conquest.txt",
    },
    {
        "id": 47297,
        "code": "parzival1",
        "title": "Parzival, Volume 1",
        "group": "mhg",
        "filename": "Parzival_pg47297.txt",
    },
    {
        "id": 47298,
        "code": "parzival2",
        "title": "Parzival, Volume 2",
        "group": "mhg",
        "filename": "Parzival_pg47298.txt",
    },
    # Iberian
    {
        "id": 8491,
        "code": "cid",
        "title": "Chronicle of the Cid",
        "group": "iberian",
        "filename": "Chronicle_of_the_Cid.txt",
    },
    # British / Frankish chronicles & monastic
    {
        "id": 1949,
        "code": "gildas",
        "title": "On the Ruin of Britain",
        "group": "oldenglish",
        "filename": "On_the_Ruin_of_Britain.txt",
    },
    {
        "id": 37848,
        "code": "oechronicles",
        "title": "Old English Chronicles",
        "group": "oldenglish",
        "filename": "Old_English_Chronicles_Giles.txt",
    },
    {
        "id": 38334,
        "code": "aelfrichomilies",
        "title": "Homilies of the Anglo-Saxon Church",
        "group": "oldenglish",
        "filename": "The_Homilies_of_the_Anglo-Saxon_Church_Containing_the_Sermones_Catholi.txt",
    },
    {
        "id": 40341,
        "code": "alfredsoliloquies",
        "title": "Alfred's Soliloquies of Augustine",
        "group": "oldenglish",
        "filename": "King_Alfreds_Old_English_Version_of_St_Augustines_Soliloquies_Turned_i.txt",
    },
    {
        "id": 48870,
        "code": "charlemagne",
        "title": "Early Lives of Charlemagne",
        "group": "medievallatin",
        "filename": "Early_Lives_of_Charlemagne_by_Eginhard_and_the_Monk_of_St_Gall_edited.txt",
    },
    {
        "id": 50778,
        "code": "malmesbury",
        "title": "William of Malmesbury's Chronicle",
        "group": "medievallatin",
        "filename": "William_of_Malmesburys_Chronicle_of_the_Kings_of_England_From_the_earl.txt",
    },
    {
        "id": 74955,
        "code": "franks",
        "title": "History of the Franks",
        "group": "medievallatin",
        "filename": "History_of_the_Franks.txt",
    },
    {
        "id": 4370,
        "code": "deedsfranks",
        "title": "The Deeds of God Through the Franks",
        "group": "medievallatin",
        "filename": "The_Deeds_of_God_Through_the_Franks.txt",
    },
    {
        "id": 37780,
        "code": "jocelin",
        "title": "Chronicle of Jocelin of Brakelond",
        "group": "medievallatin",
        "filename": "Chronicle_of_Jocelin_of_Brakelond.txt",
    },
    {
        "id": 1092,
        "code": "walesdesc",
        "title": "The Description of Wales",
        "group": "medievallatin",
        "filename": "The_Description_of_Wales.txt",
    },
    {
        "id": 1148,
        "code": "walesitin",
        "title": "Itinerary Through Wales",
        "group": "medievallatin",
        "filename": "The_Itinerary_of_Archbishop_Baldwin_Through_Wales.txt",
    },
    {
        "id": 71142,
        "code": "glanville",
        "title": "Glanville on the Laws of England",
        "group": "medievallatin",
        "filename": "A_translation_of_Glanville.txt",
    },
    {
        "id": 14268,
        "code": "calamitatum",
        "title": "Historia Calamitatum",
        "group": "medievallatin",
        "filename": "Historia_Calamitatum.txt",
    },
    {
        "id": 35977,
        "code": "abelardletters",
        "title": "Letters of Abelard and Heloise",
        "group": "medievallatin",
        "filename": "Letters_of_Abelard_and_Heloise_To_which_is_prefixd_a_particular_accoun.txt",
    },
    {
        "id": 25761,
        "code": "bernardmalachy",
        "title": "Bernard's Life of St. Malachy",
        "group": "medievallatin",
        "filename": "St_Bernard_of_Clairvauxs_Life_of_St_Malachy_of_Armagh.txt",
    },
    {
        "id": 59770,
        "code": "roswitha",
        "title": "The Plays of Roswitha",
        "group": "medievallatin",
        "filename": "The_Plays_of_Roswitha.txt",
    },
    # Devotion / lore / travel
    {
        "id": 50040,
        "code": "benedict",
        "title": "St. Benedict's Rule for Monasteries",
        "group": "medievallatin",
        "filename": "St_Benedicts_Rule_for_Monasteries.txt",
    },
    {
        "id": 66025,
        "code": "ladypoverty",
        "title": "The Lady Poverty",
        "group": "medievallatin",
        "filename": "The_Lady_Poverty.txt",
    },
    {
        "id": 6493,
        "code": "bartholomew",
        "title": "Mediaeval Lore from Bartholomew Anglicus",
        "group": "medievallatin",
        "filename": "Mediaeval_Lore_from_Bartholomew_Anglicus.txt",
    },
    {
        "id": 749,
        "code": "barlaam",
        "title": "Barlaam and Ioasaph",
        "group": "medievallatin",
        "filename": "Barlaam_and_Ioasaph.txt",
    },
    {
        "id": 14809,
        "code": "jordanes",
        "title": "Origin and Deeds of the Goths",
        "group": "medievallatin",
        "filename": "Jordanes_Origin_and_Deeds_of_the_Goths.txt",
    },
    {
        "id": 14981,
        "code": "benjamin",
        "title": "Itinerary of Benjamin of Tudela",
        "group": "medievallatin",
        "filename": "Itinerary_of_Benjamin_of_Tudela.txt",
    },
    {
        "id": 50524,
        "code": "peregrinus",
        "title": "Petrus Peregrinus on the Magnet",
        "group": "medievallatin",
        "filename": "Letter_of_Petrus_Peregrinus_on_the_Magnet_1269.txt",
    },
    # Medieval Arabic
    {
        "id": 34572,
        "code": "soulawakening",
        "title": "The Awakening of the Soul",
        "group": "medievalarabic",
        "filename": "The_Awakening_of_the_Soul.txt",
    },
    # Medieval Italian
    {
        "id": 1004,
        "code": "divinecomedy",
        "title": "The Divine Comedy",
        "group": "medievalitalian",
        "filename": "The_Divine_Comedy_Longfellow.txt",
    },
    {
        "id": 41085,
        "code": "lavitanuova",
        "title": "La Vita Nuova",
        "group": "medievalitalian",
        "filename": "The_New_Life_La_Vita_Nuova.txt",
    },
    # Classical Latin
    {
        "id": 228,
        "code": "aeneid",
        "title": "The Aeneid",
        "group": "classicallatin",
        "filename": "The_Aeneid.txt",
    },
    {
        "id": 232,
        "code": "georgics",
        "title": "The Georgics",
        "group": "classicallatin",
        "filename": "The_Georgics.txt",
    },
    {
        "id": 230,
        "code": "bucolics",
        "title": "The Bucolics and Eclogues",
        "group": "classicallatin",
        "filename": "The_Bucolics_and_Eclogues.txt",
    },
    {
        "id": 785,
        "code": "lucretius",
        "title": "On the Nature of Things",
        "group": "classicallatin",
        "filename": "On_the_Nature_of_Things.txt",
    },
    {
        "id": 10657,
        "code": "caesar",
        "title": "Caesar: Gallic War",
        "group": "classicallatin",
        "filename": "De_Bello_Gallico_and_Other_Commentaries.txt",
    },
    {
        "id": 47001,
        "code": "ciceroofficiis",
        "title": "Cicero: De Officiis",
        "group": "classicallatin",
        "filename": "De_Officiis.txt",
    },
    {
        "id": 2808,
        "code": "cicerofriendship",
        "title": "Cicero: On Friendship and Old Age",
        "group": "classicallatin",
        "filename": "Treatises_on_Friendship_and_Old_Age.txt",
    },
    {
        "id": 5432,
        "code": "horaceodes",
        "title": "Horace: Odes",
        "group": "classicallatin",
        "filename": "The_Odes_and_Carmen_Saeculare_of_Horace.txt",
    },
    {
        "id": 12140,
        "code": "romanfarm",
        "title": "Roman Farm Management: The Treatises of Cato and Varro",
        "group": "classicallatin",
        "filename": "Roman_Farm_Management_Cato_and_Varro.txt",
    },
    {
        "id": 57493,
        "code": "pliny",
        "title": "Pliny: Natural History",
        "group": "classicallatin",
        "filename": "The_Natural_History_of_Pliny_Volume_1.txt",
    },
    {
        "id": 76392,
        "code": "senecaquestions",
        "title": "Seneca: Natural Questions",
        "group": "classicallatin",
        "filename": "Physical_science_in_the_time_of_Nero.txt",
    },
    # Classical Greek
    {
        "id": 21,
        "code": "aesop",
        "title": "Aesop's Fables",
        "group": "classicalgreek",
        "filename": "Three_hundred_Aesops_fables_Translated_by_George_Fyler_Townsend.txt",
    },
    {
        "id": 6130,
        "code": "iliad",
        "title": "The Iliad",
        "group": "classicalgreek",
        "filename": "The_Iliad_pg6130.txt",
    },
    {
        "id": 1727,
        "code": "odyssey",
        "title": "The Odyssey",
        "group": "classicalgreek",
        "filename": "The_Odyssey_Rendered_into_English_prose_for_the_use_of_those_who_canno.txt",
    },
    {
        "id": 1497,
        "code": "republic",
        "title": "Plato: The Republic",
        "group": "classicalgreek",
        "filename": "The_Republic_pg1497.txt",
    },
    {
        "id": 1572,
        "code": "timaeus",
        "title": "Plato: Timaeus",
        "group": "classicalgreek",
        "filename": "Timaeus.txt",
    },
    {
        "id": 70850,
        "code": "tetrabiblos",
        "title": "Ptolemy: Tetrabiblos",
        "group": "classicalgreek",
        "filename": "Ptolemys_Tetrabiblos.txt",
    },
    {
        "code": "aratus",
        "title": "Aratus: Phaenomena",
        "group": "classicalgreek",
        "filename": "Aratus_Phaenomena.txt",
        "source": "html",
        "url": "https://www.theoi.com/Text/AratusPhaenomena.html",
        "extract_start": "From Zeus let us begin",
        "extract_end": "THE END",
    },
    {
        "code": "ontheheavens",
        "title": "Aristotle: On the Heavens",
        "group": "classicalgreek",
        "filename": "Aristotle_On_the_Heavens.txt",
        "source": "txt",
        "url": "https://classics.mit.edu/Aristotle/heavens.mb.txt",
        "extract_start": "On the Heavens\nBy Aristotle",
        "extract_end": "THE END",
    },
    {
        "code": "almageststars",
        "title": "Ptolemy's Catalogue of Stars",
        "group": "classicalgreek",
        "filename": "Ptolemy_Catalogue_of_Stars.txt",
        "source": "pdf",
        "url": "https://archive.org/download/ptolemyscataloqu00ptoluoft/ptolemyscataloqu00ptoluoft.pdf",
        "extract_start": "The following work embraces the results",
        "extract_end_re": r"CATALOGUE\s+II\.",
        "include_end": False,
        "keep_line_breaks": True,
    },
    {
        "id": 2680,
        "code": "meditations",
        "title": "Marcus Aurelius: Meditations",
        "group": "classicalgreek",
        "filename": "Meditations.txt",
    },
    {
        "id": 31,
        "code": "sophocles",
        "title": "Oedipus the King, Oedipus at Colonus, and Antigone",
        "group": "classicalgreek",
        "filename": "Plays_of_Sophocles_Oedipus_and_Antigone.txt",
    },
    {
        "id": 830,
        "code": "argonautica",
        "title": "The Argonautica",
        "group": "classicalgreek",
        "filename": "The_Argonautica.txt",
    },
    # Ancient Sanskrit
    {
        "id": 12169,
        "code": "sakoontala",
        "title": "Sakoontala",
        "group": "ancientsanskrit",
        "filename": "Sakoontala_Or_The_Lost_Ring.txt",
    },
    {
        "code": "suryasiddhanta",
        "title": "The Surya Siddhanta",
        "group": "ancientsanskrit",
        "filename": "Surya_Siddhanta_Burgess.txt",
        "source": "epub",
        "url": (
            "https://archive.org/download/surya-siddhanta-burgess-translation_202109/"
            "surya%20siddhanta%20BURGESS%20Translation%20%20%20%20%20.epub"
        ),
    },
]
